openapi: 3.0.3
info:
  title: Roofly App
  version: 1.0.0
servers:
  - url: https://api.roofly.com
tags:
  - name: v1
paths:
  /roofly-sso-service/v1/user/getUserById/{id2}:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/user/getUserById/{id2}
      operationId: get_id_v1_user_getUserById_id2
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: "110469"
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/profiles:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/profiles
      operationId: get_roofly_sso_service_v1_profiles
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: string
          example: "110469"
        - name: currentUserId
          in: query
          required: false
          schema:
            type: string
          example: undefined
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/public/property/{id2}:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/public/property/{id2}
      operationId: get_roofly_sso_service_v1_public_property_id2
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: "267309"
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/connections/{id2}/{id3}:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/connections/{id2}/{id3}
      operationId: get_roofly_sso_service_v1_connections_id2_id3
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: getConnectionsByUser
        - name: id3
          in: path
          required: true
          schema:
            type: string
          example: "110469"
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/saveSearch/all/{id2}:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/saveSearch/all/{id2}
      operationId: get_roofly_sso_service_v1_saveSearch_all_id2
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: "110469"
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/saveSearch/count/{id2}:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/saveSearch/count/{id2}
      operationId: get_roofly_sso_service_v1_saveSearch_count_id2
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: "110469"
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/public/categories/search:
    post:
      tags:
        - v1
      summary: POST /roofly-sso-service/v1/public/categories/search
      operationId: post_roofly_sso_service_v1_public_categories_search
      parameters:

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1PostRequest"
            examples:
              fromHar:
                value:
                  pageNo: 0
                  pageSize: 10
                  totalPages: 0
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/connections/{id2}:
    post:
      tags:
        - v1
      summary: POST /roofly-sso-service/v1/connections/{id2}
      operationId: post_roofly_sso_service_v1_connections_id2
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: rejectConnectionRequest
        - name: connectionId
          in: query
          required: false
          schema:
            type: string
          example: "308"
        - name: userId
          in: query
          required: false
          schema:
            type: string
          example: "110469"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1PostRequest"
            examples:
              fromHar:
                value:
                  receiverId: 101776
                  requesterId: 110469
                  userId: 110469
      responses:
        "200":
          description: Success
    delete:
      tags:
        - v1
      summary: DELETE /roofly-sso-service/v1/connections/{id2}
      operationId: delete_roofly_sso_service_v1_connections_id2
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: removeConnection
        - name: connectionId
          in: query
          required: false
          schema:
            type: string
          example: "312"
        - name: userId
          in: query
          required: false
          schema:
            type: string
          example: "110469"
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/public/property-videos:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/public/property-videos
      operationId: get_roofly_sso_service_v1_public_property_videos
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: string
          example: "1"
        - name: pageSize
          in: query
          required: false
          schema:
            type: string
          example: "1"
        - name: country
          in: query
          required: false
          schema:
            type: string
          example: AE
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/connections/{id2}/{id3}/{id4}:
    get:
      tags:
        - v1
      summary: GET /roofly-sso-service/v1/connections/{id2}/{id3}/{id4}
      operationId: get_roofly_sso_service_v1_connections_id2_id3_id4
      parameters:
        - name: id2
          in: path
          required: true
          schema:
            type: string
          example: getConnectionStatus
        - name: id3
          in: path
          required: true
          schema:
            type: string
          example: "110469"
        - name: id4
          in: path
          required: true
          schema:
            type: string
          example: "101776"
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/posts/create:
    post:
      tags:
        - v1
      summary: POST /roofly-sso-service/v1/posts/create
      operationId: post_roofly_sso_service_v1_posts_create
      parameters:

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1PostRequest"
            examples:
              fromHar:
                value:
                  content: |-
                    Check out this property by Ranjith Kumar

                    https://roofly.com/roofly-homes/properties/267309
                  images: []
                  authorType: agent
                  authorId: "110469"
                  agencyId: 0
      responses:
        "200":
          description: Success
  /roofly-sso-service/v1/user/update:
    put:
      tags:
        - v1
      summary: PUT /roofly-sso-service/v1/user/update
      operationId: put_roofly_sso_service_v1_user_update
      parameters:

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1PutRequest"
            examples:
              fromHar:
                value:
                  id: "110469"
                  name: ghouse mohammed 1
                  email: mohammedghouse86.backup@gmail.com
                  phone: "+966578139964"
      responses:
        "200":
          description: Success
components:
  schemas:
    V1PostRequest:
      type: object
      properties:
        pageNo:
          type: integer
        pageSize:
          type: integer
        totalPages:
          type: integer
      required:
        - pageNo
        - pageSize
        - totalPages
    V1PutRequest:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
      required:
        - id
        - name
        - email
        - phone
